const BASE_URL = 'https://e14segundavueltapresidente.registraduria.gov.co';

const DEPARTMENTS = [
  { name: 'AMAZONAS', code: '60' },
  { name: 'ANTIOQUIA', code: '01' },
  { name: 'ARAUCA', code: '40' },
  { name: 'ATLANTICO', code: '03' },
  { name: 'BOGOTA D.C.', code: '16' },
  { name: 'BOLIVAR', code: '05' },
  { name: 'BOYACA', code: '07' },
  { name: 'CALDAS', code: '09' },
  { name: 'CAQUETA', code: '44' },
  { name: 'CASANARE', code: '46' },
  { name: 'CAUCA', code: '11' },
  { name: 'CESAR', code: '12' },
  { name: 'CHOCO', code: '17' },
  { name: 'CONSULADOS', code: '88' },
  { name: 'CORDOBA', code: '13' },
  { name: 'CUNDINAMARCA', code: '15' },
  { name: 'GUAINIA', code: '50' },
  { name: 'GUAVIARE', code: '54' },
  { name: 'HUILA', code: '19' },
  { name: 'LA GUAJIRA', code: '48' },
  { name: 'MAGDALENA', code: '21' },
  { name: 'META', code: '52' },
  { name: 'NARIÑO', code: '23' },
  { name: 'NORTE DE SAN', code: '25' },
  { name: 'PUTUMAYO', code: '64' },
  { name: 'QUINDIO', code: '26' },
  { name: 'RISARALDA', code: '24' },
  { name: 'SAN ANDRES', code: '56' },
  { name: 'SANTANDER', code: '27' },
  { name: 'SUCRE', code: '28' },
  { name: 'TOLIMA', code: '29' },
  { name: 'VALLE', code: '31' },
  { name: 'VAUPES', code: '68' },
  { name: 'VICHADA', code: '72' },
];

module.exports = { BASE_URL, DEPARTMENTS };
